version: '3'

services:
  #the service name 
  database:
    #MYSQL VERSION
    image: mysql:8.0.29
    #the database container name 
    container_name: database
    environment:
      # environments which if you use password for ur database u should add it here which i dont thats why im using allow empty password and including my database name
      MYSQL_DATABASE: etablissement
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"
    ports:
      #mysql port
      - 3306
    volumes:
      # its just  a link to the sql on the server i think it should stay the same 
      - dockerAngularSpringDatabaseData:/var/lib/mysql
    networks:
      #my database network name
      - backendNetwork
  # spring boot service name 
  TYPEABACK:
    # your jdk version
    image: openjdk:8-alpine
    # container name 
    container_name: TYPEABACK
    ports:
      # spring port
      - 8080:8080
    environment:
      # datasource url to link database with backend 
      SPRING_DATASOURCE_URL: jdbc:mysql://database:3306/etablissement?useSSL=false
    depends_on:
      # the database service name 
      - database
    volumes:
      # where your jar is located and used 
      - ./TYPEABACK/typea/target/typea-0.0.1-SNAPSHOT.jar:/springboot-docker.jar
    command: [ "java", "-jar", "springboot-docker.jar" ]
    networks:
      # networks used 
      - backendNetwork
      - frontendNetwork

  TYPEAFRONT:
    # nginx image
    image: nginx:alpine
    # front contaienr name
    container_name: TYPEAFRONT
    ports:
      # nginx ports 
      - 80:80
    depends_on:
      #back linkage
      - TYPEABACK
    volumes:
      #where my nginx.conf is located
      - ./TYPEAFRONT/nginx.conf:/etc/nginx/nginx.conf
      #dist file location
      - ./TYPEAFRONT/dist/frontend/:/usr/share/nginx/html
    networks:
      # front network name
      - frontendNetwork

volumes:
  dockerAngularSpringDatabaseData:


networks:
  # used networks
  backendNetwork:
  frontendNetwork:
